### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by nobody2231** [Linzy0227/PDMINet#1]
bro，the resources was gone

**Comment by Linzy0227** [comment]
> bro，the resources

**Comment by Linzy0227** [comment]
> bro，the resources was gone

We will provide the code after the paper is accepted.

**Comment by haha256199** [comment]
BraTS2018、BraTS2019和BraTS2020这三个公开数据集的测试集和验证集没有标签，该如何去计算Dice和Hausdorff距离这两个指标

**Comment by Linzy0227** [comment]
> BraTS2018、BraTS2019和BraTS2020这三个公开数据集的测试集和验证集没有标签，该如何去计算Dice和Hausdorff距离这两个指标

测试集我们拿不到，验证集有标签，但是没提供，需要将验证的结果提供到在线网站进行评分
<img width="692" alt="Image" src="https://github.com/user-attachments/assets/ca8edca8-067c-4f08-b4e5-2a711a28413d" />
